[package]
name = "rust_test"
version = "0.1.0"
authors = ["yumit412 <yumit412@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
async-std = "1.5.0"
modbus = "1.0.3"
